---
# tasks file for helmfile | EL Family

- name: EL Family | Downloading binary for {{ helmfile_app }} {{ helmfile_version }} to {{ helmfile_bin_path }}
  ansible.builtin.get_url:
    url: "{{ helmfile_dl_url }}"
    dest: "{{ helmfile_bin_path }}/{{ helmfile_app }}"
    owner: "{{ helmfile_file_owner }}"
    group: "{{ helmfile_file_group }}"
    mode: "{{ helmfile_file_mode }}"
