---
# tasks file for helmfile | EL Family

- name: EL Family | Downloading and extracting {{ helmfile_app }} {{ helmfile_version }}
  ansible.builtin.unarchive:
    src: "{{ helmfile_dl_url }}"
    dest: "{{ helmfile_bin_path }}"
    extra_opts:
      - "{{ helmfile_app }}"
    remote_src: yes
    owner: "{{ helmfile_file_owner }}"
    group: "{{ helmfile_file_group }}"
    mode: "{{ helmfile_file_mode }}"
